# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prettier checks
on:
  push:
    branches: ['main', '67-add-svelte-check-to-github-workflows---styleguide']
  pull_request:
    branches: ['main', '67-add-svelte-check-to-github-workflows---styleguide']

jobs:
  prettier:
    name: Prettier

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check formatting with Prettier
        run: npm run prettier:check:ci
